//目前空橢圓 擦子 以及隱藏 無法
var canvas = document.createElement("canvas");
canvas.id = "canvas";
canvas.className='donothing';
var body = document.body,
    html = document.documentElement;

var height = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );
canvas.height = height;
canvas.width = window.innerWidth;

var ctx = canvas.getContext("2d");
ctx.fillStyle = "black";
ctx.strokeStyle = "black";
//ctx.fillRect(0,0,window.innerWidth,window.innerHeight);
var button_donothing = document.createElement("div");
function createELE(tag,classname,id){
    var ret = document.createElement(tag);
    ret.className +=classname;
    ret.id = id;
    ret.style.zIndex='999999';
    return ret;
}
var main_wrapper = createELE("div","main_wrapper","");
var tool_wrapper = createELE("div","tool_wrapper","");
var button_hide_toolbar = createELE("div","Button","hide_toolbar");
var button_donothing = createELE("div","Button","donothing");
var button_download = createELE("div","Button","download");
var button_hide = createELE("div","Button","hide");
var button_fill = createELE("div","Button","fill");
var button_pen = createELE("div","Button","pen");
var button_eraser = createELE("div","Button","eraser");
var button_rectangle = createELE("div","Button","rectangle");
var button_circle = createELE("div","Button","circle");
var button_sprinkle = createELE("div","Button","sprinkle");
var button_text = createELE('div',"Button",'text');
var button_clean = createELE('div',"Button",'clean');
var button_save = createELE("div","Button","save");
var button_clear_storage = createELE('div',"Button","clearAll");
var color_picker = createELE('input','','color_picker');
button_hide_toolbar.textContent = '現';
button_donothing.textContent='無';
button_download.textContent='載';
button_hide.textContent='藏';
button_fill.textContent='滿';
button_pen.textContent='筆';
button_eraser.textContent='擦';
button_rectangle.textContent='方';
button_circle.textContent='圓';
button_sprinkle.textContent='噴';
button_text.textContent='字';
button_clean.textContent='清';
button_save.textContent = "存";
button_clear_storage.textContent ='清存';
tool_wrapper.style.zIndex='999998';
color_picker.setAttribute('type','color');
main_wrapper.style.position='';
tool_wrapper.appendChild(button_hide_toolbar);
tool_wrapper.appendChild(button_donothing);
tool_wrapper.appendChild(button_download);
tool_wrapper.appendChild(button_hide);
tool_wrapper.appendChild(button_fill);
tool_wrapper.appendChild(button_pen);
tool_wrapper.appendChild(button_eraser);
tool_wrapper.appendChild(button_rectangle);
tool_wrapper.appendChild(button_circle);
tool_wrapper.appendChild(button_sprinkle);
tool_wrapper.appendChild(button_text);
tool_wrapper.appendChild(button_clean);
tool_wrapper.appendChild(button_save);
tool_wrapper.appendChild(button_clear_storage);
main_wrapper.appendChild(tool_wrapper);
canvas.style.zIndex='999990';
tool_wrapper.appendChild(color_picker);
main_wrapper.appendChild(canvas);
var body = document.getElementsByTagName("body")[0];
body.appendChild(main_wrapper);